/**
 * The one and only place that calls streamText.
 *
 * It has exactly two jobs:
 *   1. Translate LLMRequest into SDK parameters (strictly limiting what gets passed — don't
 *      leak the SDK's full capabilities to the layer above)
 *   2. Normalize fullStream into our own LLMEvent
 *
 * ── A few deliberate choices ──
 * - `maxRetries: 0`: the SDK's retry has no UI feedback, doesn't distinguish error types,
 *   and ignores retry-after. We do it ourselves in retry.ts, wrapped around the whole
 *   stream.
 * - No `stopWhen`: the AI SDK defaults to a single step. Multiple turns are driven by the
 *   main loop — compaction, max turns, permission blocks and rereading history all have to
 *   happen between turns; hand that to the SDK and we never get control back.
 * - text / reasoning ids get a fallback generated by us: some compatible endpoints don't
 *   provide ids at all, and relying on them would string every part into one.
 * - Responses text metadata stays separate from those fallback IDs. Raw chunks are used
 *   only to reject unknown phases the SDK would otherwise silently skip, never replayed.
 */
import { createRequestMetrics, withRequestMetrics, finishRequestMetrics, captureCacheUsage } from "./request-metrics.ts"
import type { CacheUsage } from "./cache/index.ts"
import { reportUsage } from "./usage.ts"
import { jsonSchema, streamText, tool, type ModelMessage, type TextStreamPart, type ToolSet } from "ai"
import { adaptTools } from "./adapt-tools.ts"
import type { LLMRegistry } from "./registry.ts"
import { toInstructions, toModelMessages } from "./to-model-messages.ts"
import type { LLMEvent, LLMRequest, ModelInfo, Tokens, ResponsesTextMetadata } from "./types.ts"
import { logger } from "../util/log.ts"

const log = logger("llm")

/**
 * ★ SDK warnings **always go to the log file, never to the terminal**.
 *
 * The default implementation uses `process.emitWarning`, which is stderr — written at
 * wherever the cursor sits inside the live area, behind its back. One warning tears the
 * frame apart (symptom: a few lines of `at emitWarning (/$bunfs/root/...)` wedged into
 * the middle of the conversation, and the live area's next erase starts from the wrong
 * row, leaving a torn copy of the frame stuck in the scrollback — see cli/live.ts). It
 * also repeats with every request, so a few exchanges in, the screen is wrecked.
 *
 * Turning it off isn't hiding the problem: with `ALFA_DEBUG=1` they still land in the log,
 * and this and util/warnings.ts (process warnings) are the **only two** places in this
 * process allowed to decide "where warnings go".
 */
const globals = globalThis as { AI_SDK_LOG_WARNINGS?: unknown }
globals.AI_SDK_LOG_WARNINGS = (options: { warnings?: unknown[]; provider?: string; model?: string }) => {
  log.warn("sdk warning", {
    provider: options.provider,
    model: options.model,
    warnings: options.warnings,
  })
}

export interface StreamHandle {
  info: ModelInfo
  events: AsyncGenerator<LLMEvent>
}

/**
 * How "not a single tool may be called on this step" lands on Anthropic.
 *
 * ── Why it's needed ──
 * The layer above expresses "tools disabled" as `activeTools: []` (see the hit-the-cap
 * turn in agent/loop.ts, agent/compact.ts). The SDK translates that
 * into `toolChoice: "none"`, and @ai-sdk/anthropic's prepareTools handles none and empty
 * tools identically: `return { tools: undefined, toolChoice: undefined }` — **the whole
 * tools field disappears**.
 *
 * ⚠ And Anthropic's Messages API has a hard rule: if a `tool_use` / `tool_result` block
 *   has appeared anywhere in the request's history, tools **must** be declared. Put the two
 *   together and it's a 400.
 *
 * Here's how it played out: a turn runs the full 100 steps (see prompt/max-steps.ts), the
 * history is all tool calls, and that turn's final wrap-up request — "tools off, report
 * progress in plain text" — gets rejected outright. The user waited a long time and got an
 * error, and that turn is **precisely the one designed to avoid a "half-finished
 * session"**. The openai-chat path doesn't care about this, so it only shows up on one
 * provider.
 *
 * ── Why a fake tool and not something else ──
 * For the request to be legal, tools must be non-empty; and any **real** tool put in there
 * might get called, which is no longer disabling. So we put in an empty shell that is
 * declared unmistakably and, if called anyway, only answers "no tools on this step": the
 * request is legal, the history is intact, and there's not one byte of side effect.
 *
 * Compaction and summaries never get here — their messages are a single freshly built
 * user message, with no tool blocks in history, so tools being absent is perfectly legal
 * (see hasToolCalls below).
 *
 * A word on caching while we're at it: this step's tools prefix differs from the usual one,
 * so it's bound to miss. That isn't a new cost — the hit-the-cap turn stuffs
 * MAX_STEPS_PROMPT into system, so the prefix was already broken.
 */
const TOOLS_DISABLED: ToolSet = {
  tools_unavailable: tool({
    description:
      "Not callable. It is declared only because this request's history contains tool calls and the API " +
      "requires at least one tool to be defined. Answer with text.",
    inputSchema: jsonSchema({ type: "object", properties: {}, additionalProperties: false }) as never,
    execute: async () => "No tools are available on this step. Answer with text only.",
  }),
}

/**
 * Whether history contains tool blocks. If it does, tools can't be absent — see
 * TOOLS_DISABLED.
 *
 * **Exported** so it can be tested directly: this one line is the entire criterion for
 * "fake tool, or disable as usual", and getting it wrong is expensive in both directions —
 * a wrong false means a 400 on the hit-the-cap turn; a wrong true means compaction and
 * summary requests suddenly carry a tool the model shouldn't see.
 */
export function hasToolCalls(messages: ModelMessage[]): boolean {
  return messages.some((message) => {
    if (message.role === "tool") return true
    if (!Array.isArray(message.content)) return false
    return message.content.some((part) => part.type === "tool-call" || part.type === "tool-result")
  })
}

export function stream(registry: LLMRegistry, request: LLMRequest): StreamHandle {
  const requestId = crypto.randomUUID()
  const resolved = registry.resolve(`${request.model.providerID}/${request.model.modelID}`, {
    thinking: request.thinking,
    ...(request.effort ? { effort: request.effort } : {}),
  })

  const nativeApplyPatch = resolved.replayResponses === true && resolved.info.promptProfile === "openai-codex"
  const tools: ToolSet = adaptTools({
    tools: request.tools,
    makeToolContext: request.makeToolContext,
    nativeApplyPatch,
  })

  const messages: ModelMessage[] = toModelMessages(request.messages, resolved.replayReasoning ?? "signed", resolved.replayResponses === true, nativeApplyPatch, resolved.info.images !== false)
  const instructions = toInstructions(request.system, resolved.singleSystem ?? false)

  /** Told "call none", yet history has tool blocks — see the whole TOOLS_DISABLED note */
  const shimTools = request.activeTools?.length === 0 && hasToolCalls(messages)

  const metrics = createRequestMetrics()
  const result = withRequestMetrics(metrics, () => streamText({
    model: resolved.model,
    // v7: system must go through instructions; putting it in messages throws
    // InvalidPromptError
    ...(instructions.length > 0 ? { instructions } : {}),
    messages,
    tools: shimTools ? TOOLS_DISABLED : tools,
    // ★ On the fake-tool path neither activeTools nor toolChoice **may be passed** — pass
    //   either one and the provider wipes tools again, and this shim is for nothing
    ...(shimTools ? {} : request.activeTools ? { activeTools: request.activeTools as never } : {}),
    ...(shimTools ? {} : request.activeTools?.length === 0 ? { toolChoice: "none" as const } : {}),
    ...(resolved.temperature !== undefined ? { temperature: resolved.temperature } : {}),
    // Same convention as the window reservation: a saved output cap must not get cut down
    // by an invisible 32k.
    maxOutputTokens: resolved.info.limit.output,
    ...(resolved.providerOptions ? { providerOptions: resolved.providerOptions } : {}),
    abortSignal: request.abortSignal,
    // The SDK can silently skip unknown item phases; raw chunks let us reject those explicitly.
    ...(resolved.replayResponses || metrics ? { includeRawChunks: true } : {}),
    maxRetries: 0, // we retry ourselves, see retry.ts
    // ⚠ Must be passed. streamText's onError **defaults to console.error**, while the
    //   error also enters fullStream as an error part — in other words, if it isn't
    //   overridden, every 429 that retry.ts would quietly retry away first spews a whole
    //   SDK stack trace onto stderr and wrecks the UI being rendered. Here it goes to the
    //   debug log instead.
    onError: ({ error }) => log.error("stream error", { message: String(error) }),
  }))

  const started = Date.now()
  async function* measured(): AsyncGenerator<LLMEvent> {
    let tokens: Tokens | undefined
    let observedCache: CacheUsage | undefined
    let rawUsage: unknown
    let measuredInputTokens: number | null = null
    let measuredOutputTokens: number | null = null
    try {
      for await (const event of normalize(result.fullStream, resolved.replayResponses === true, (raw, inputTokens, cacheUsage, outputTokens) => { rawUsage = raw; measuredInputTokens = inputTokens ?? null; observedCache = cacheUsage; measuredOutputTokens = outputTokens ?? null }, raw => captureCacheUsage(metrics, raw))) {
        if (event.type === "step-finish") tokens = event.tokens
        yield event
      }
    } finally {
      reportUsage({
        model: request.model, effort: metrics?.effort, requestId, execution: request.execution, tokens,
        measuredOutputTokens,
        measuredInputTokens: measuredInputTokens !== null && !resolved.info.cacheInInput
          ? measuredInputTokens + (tokens?.cache.read ?? 0) : measuredInputTokens,
        observedCache: observedCache ? {
          ...observedCache,
          totalInputTokens: observedCache.totalInputTokens !== null && !resolved.info.cacheInInput
            ? observedCache.cacheReadTokens === null ? null : observedCache.totalInputTokens + observedCache.cacheReadTokens
            : observedCache.totalInputTokens,
        } : undefined,
        elapsedMs: Date.now() - started, cacheInInput: resolved.info.cacheInInput === true,
        ...(metrics ? { cache: finishRequestMetrics(metrics, rawUsage, observedCache) } : {}),
      })
    }
  }
  return { info: resolved.info, events: measured() }
}

/**
 * fullStream → LLMEvent.
 *
 * Unrecognized parts are dropped (source / file / custom / approval etc.); Responses raw
 * chunks are inspected only for unsupported phases.
 * Dropping is deliberate: adding a case is an explicit decision; passing through by default
 * is where an abstraction layer starts to rot.
 *
 * Exported so it can be fed event sequences and tested directly — bugs in this half of the
 * module (e.g. scavenging the signature) don't error on the spot; they only turn into a
 * warning and a lost chunk of thinking on the **next turn**.
 */
export async function* normalize(fullStream: AsyncIterable<TextStreamPart<ToolSet>>, responses = false, onRawUsage?: (raw: unknown, inputTokens?: number, cacheUsage?: CacheUsage, outputTokens?: number) => void, onRawChunk?: (raw: unknown) => void): AsyncGenerator<LLMEvent> {
  let synthetic = 0
  const nextID = (prefix: string) => `${prefix}_${synthetic++}`
  /** Fallback mapping for when the provider gives no id */
  let currentText: string | undefined
  let currentReasoning: string | undefined
  /**
   * The signature for this stretch of thinking.
   *
   * ★ It hangs on **a reasoning-delta with empty text** (the SDK translates Anthropic's
   *   `signature_delta` into that), **not on reasoning-end**. Looking only in the end
   *   event never finds it — and thinking without a signature is dropped whole by the SDK
   *   with a warning when replayed ("unsupported reasoning metadata"), one warning per
   *   piece of thinking in history.
   */
  let pendingSignature: string | undefined

  for await (const part of fullStream) {
    switch (part.type) {
      case "raw": {
        onRawChunk?.(part.rawValue)
        if (responses) validateResponsePhase(part.rawValue)
        break
      }
      case "text-start":
        currentText = part.id || nextID("txt")
        yield { type: "text-start", id: currentText, ...(responses ? { responses: responseTextMetadata(part.providerMetadata) } : {}) }
        break
      case "text-delta":
        if (!currentText) {
          currentText = part.id || nextID("txt")
          yield { type: "text-start", id: currentText }
        }
        yield { type: "text-delta", id: part.id || currentText, text: part.text }
        break
      case "text-end":
        yield { type: "text-end", id: part.id || currentText || nextID("txt"), ...(responses ? { responses: responseTextMetadata(part.providerMetadata) } : {}) }
        currentText = undefined
        break

      case "reasoning-start":
        currentReasoning = part.id || nextID("rsn")
        pendingSignature = undefined
        yield { type: "reasoning-start", id: currentReasoning }
        break
      case "reasoning-delta": {
        if (!currentReasoning) {
          currentReasoning = part.id || nextID("rsn")
          yield { type: "reasoning-start", id: currentReasoning }
        }
        pendingSignature = extractSignature(part.providerMetadata) ?? pendingSignature
        // The delta carrying the signature has empty text; no need to emit it
        if (part.text.length > 0) yield { type: "reasoning-delta", id: part.id || currentReasoning, text: part.text }
        break
      }
      case "reasoning-end": {
        const signature = extractSignature(part.providerMetadata) ?? pendingSignature
        yield {
          type: "reasoning-end",
          id: part.id || currentReasoning || nextID("rsn"),
          ...(signature ? { signature } : {}),
        }
        currentReasoning = undefined
        pendingSignature = undefined
        break
      }

      case "tool-input-start":
        yield { type: "tool-input-start", callID: part.id, tool: part.toolName }
        break
      case "tool-call":
        yield { type: "tool-call", callID: part.toolCallId, tool: part.toolName, input: part.input }
        break
      case "tool-result":
        yield {
          type: "tool-result",
          callID: part.toolCallId,
          tool: part.toolName,
          // Native apply_patch wraps the executor's text only for the Responses wire.
          // Storing that wrapper would double-wrap it when the history is replayed.
          output: part.toolName === "apply_patch" && typeof part.output === "object" && part.output !== null && "status" in part.output && part.output.status === "completed" && "output" in part.output && typeof part.output.output === "string"
            ? part.output.output
            : typeof part.output === "string" ? part.output : JSON.stringify(part.output),
        }
        break
      case "tool-error":
        yield {
          type: "tool-error",
          callID: part.toolCallId,
          tool: part.toolName,
          error: errorText(part.error),
        }
        break

      case "start-step":
        yield { type: "step-start" }
        break
      case "finish-step":
        onRawUsage?.(part.usage.raw, part.usage.inputTokens, observedCacheUsage(part.usage), part.usage.outputTokens)
        yield { type: "step-finish", finishReason: part.finishReason, tokens: toTokens(part.usage) }
        break

      case "error":
        yield { type: "error", error: part.error instanceof Error ? part.error : new Error(errorText(part.error)) }
        break

      default:
        // Explicitly ignored: start / finish / abort / source / file / raw / custom /
        // tool-input-delta / tool-input-end / approval-* / tool-output-denied
        break
    }
  }
}

/** Anthropic's thinking signature. Must go back verbatim when replaying history, or 400. */
function extractSignature(metadata: unknown): string | undefined {
  if (!metadata || typeof metadata !== "object") return undefined
  const anthropic = (metadata as Record<string, unknown>)["anthropic"]
  if (!anthropic || typeof anthropic !== "object") return undefined
  const signature = (anthropic as Record<string, unknown>)["signature"]
  return typeof signature === "string" ? signature : undefined
}

/** Missing SDK fields remain unknown in diagnostics, even though legacy billing uses zero. */
export function observedCacheUsage(usage: {
  inputTokens?: number
  inputTokenDetails?: { cacheReadTokens?: number; cacheWriteTokens?: number }
}): CacheUsage {
  const count = (value: number | undefined) => typeof value === "number" && Number.isSafeInteger(value) && value >= 0 ? value : null
  return {
    totalInputTokens: count(usage.inputTokens),
    cacheReadTokens: count(usage.inputTokenDetails?.cacheReadTokens),
    cacheWriteTokens: count(usage.inputTokenDetails?.cacheWriteTokens),
  }
}

function toTokens(usage: {
  inputTokens?: number
  outputTokens?: number
  totalTokens?: number
  inputTokenDetails?: { cacheReadTokens?: number; cacheWriteTokens?: number }
  outputTokenDetails?: { reasoningTokens?: number }
}): Tokens {
  const safe = (value: number | undefined) => (Number.isFinite(value) && value! > 0 ? value! : 0)
  return {
    input: safe(usage.inputTokens),
    output: safe(usage.outputTokens),
    reasoning: safe(usage.outputTokenDetails?.reasoningTokens),
    cache: {
      read: safe(usage.inputTokenDetails?.cacheReadTokens),
      write: safe(usage.inputTokenDetails?.cacheWriteTokens),
    },
    ...(safe(usage.totalTokens) > 0 ? { total: safe(usage.totalTokens) } : {}),
  }
}

function errorText(error: unknown): string {
  if (error instanceof Error) return error.message
  if (typeof error === "string") return error
  try {
    return JSON.stringify(error)
  } catch {
    return String(error)
  }
}

/** Unknown phases must fail visibly, even when the SDK treats their chunk as unknown. */
function validateResponsePhase(raw: unknown): void {
  if (!raw || typeof raw !== "object") return
  const event = raw as { type?: string; item?: { type?: string; phase?: unknown } }
  if (event.type !== "response.output_item.added" && event.type !== "response.output_item.done") return
  if (event.item?.type !== "message") return
  const phase = event.item.phase
  if (phase != null && phase !== "commentary" && phase !== "final_answer") {
    throw new Error(`Unsupported Responses assistant phase: ${String(phase)}`)
  }
}

function responseTextMetadata(metadata: unknown): ResponsesTextMetadata | undefined {
  const value = (metadata as { openai?: { itemId?: unknown; phase?: unknown } } | undefined)?.openai
  if (!value) return undefined
  const phase = value.phase
  if (phase != null && phase !== "commentary" && phase !== "final_answer") {
    throw new Error(`Unsupported Responses assistant phase: ${String(phase)}`)
  }
  const itemId = typeof value.itemId === "string" ? value.itemId : undefined
  if (itemId === undefined && phase === undefined) return undefined
  return { ...(itemId !== undefined ? { itemId } : {}), ...(phase !== undefined ? { phase } : {}) }
}
