/**
 * ★ The LLM integration boundary.
 *
 * This file **must not** import "ai" or "@ai-sdk/*" — it is the only LLM vocabulary
 * src/agent knows. SDK types may appear only in the other files under src/llm.
 *
 * ── Why events get our own names instead of passing the SDK's through ──
 * The biggest rework risk is building the abstraction layer as a pass-through layer. If
 * LLMEvent just copied the shape of the AI SDK's fullStream parts, then:
 *   - hooking up our own provider (the future memory layer / billing gateway) wouldn't
 *     match the shape;
 *   - one major AI SDK upgrade renaming events would collapse everything downstream (we've
 *     already jumped from v6 to v7).
 * So: our own names, our own fields — even text/reasoning ids get a fallback generated by
 * us, rather than relying on the provider to supply them.
 */
import type { ToolContext, ToolDef } from "../tool/types.ts"

// ─────────────────────────────────────────────── Model identity

export interface ModelRef {
  providerID: string
  modelID: string
}

/**
 * Default window when model metadata can't be found.
 *
 * 256k is deliberately a middle fallback for compatible endpoints whose model metadata
 * is unknown. Known first-party models keep their table values, and setup/settings let
 * the user record the real value without editing config.json. `/context` states whether
 * the number is known or guessed.
 */
export const DEFAULT_CONTEXT_LIMIT = 256_000

export interface ModelInfo {
  ref: ModelRef
  /** Context and output budget. Defaults if unknown; see DEFAULT_CONTEXT_LIMIT. */
  limit: { context: number; output: number }
  /**
   * Where the limit above came from: the model's own metadata / what the user wrote in
   * config / the fallback default.
   *
   * Used only so `/context` can tell the truth. A gauge that draws a guessed window as a
   * progress bar is likelier to lead someone to a wrong decision than no gauge at all.
   */
  limitSource?: "model" | "config" | "default"
  supportsThinking: boolean
  /** For choosing the system prompt template */
  promptTemplate: "anthropic" | "default"
  /** Explicit capability profile; absent keeps the provider's established template. */
  promptProfile?: "generic" | "anthropic" | "openai-codex"
  /**
   * Whether the input tokens **as they reach us** already include the cache-hit portion.
   *
   * ★ This is about the number the AI SDK hands over, **not the provider's raw API
   *   convention**. The two can differ, and confusing them is the one way this field
   *   gets filled in wrong:
   *
   *     Anthropic's raw API reports input_tokens and cache_read_input_tokens separately,
   *     so going by the docs it's false — which is what it once was, and it was wrong.
   *     @ai-sdk/anthropic's convertAnthropicUsage has already added them up once
   *     (inputTokens.total = input_tokens + cache_creation + cache_read), and ai core
   *     takes exactly .total. By the time it gets here, it's already included.
   *
   *   So before filling it in, look at how the SDK layer computes it, not at what the
   *   provider's docs say.
   *
   * The two conventions can't be told apart from the numbers themselves, and a wrong guess
   * is an error by a whole multiple: treat it as excluding when it actually includes, and
   * context usage is counted double, so compaction fires halfway. Hence providers must
   * declare it explicitly — whoever writes a new provider has to stop and think about it.
   */
  cacheInInput: boolean
  /**
   * false = this model can't take image input: stored images reach it as a one-line text
   * note instead (see toModelMessages). Absent = it can. Providers set it explicitly; see
   * ModelConfig.images in config.ts for why a wrong yes is the expensive direction.
   */
  images?: boolean
}

/**
 * How hard the model should think — **one scale for all three wire protocols**.
 *
 * The five names are Anthropic's `output_config.effort` levels; Responses calls the
 * same knob `reasoning.effort`, Chat Completions `reasoning_effort`. Each adapter maps
 * this scale onto what its endpoint accepts (see the providers/*.ts headers). Unset is
 * not a sixth level: it means "send nothing, the provider's default applies" — which is
 * not the same everywhere (high on most Claude models, medium on Opus 5.5), so no
 * level can stand in for it.
 *
 * ⚠ The scale deliberately stops at these five. OpenAI's `none` / `minimal` overlap
 *   with turning thinking off, which already has its own switch (`/think`); a sixth
 *   name that only one protocol understands would be a setting that silently does
 *   nothing on the other two.
 */
export const REASONING_EFFORTS = ["low", "medium", "high", "xhigh", "max"] as const
export type ReasoningEffort = (typeof REASONING_EFFORTS)[number]

export function isReasoningEffort(value: unknown): value is ReasoningEffort {
  return typeof value === "string" && (REASONING_EFFORTS as readonly string[]).includes(value)
}

/**
 * The highest level in `supported` that is not above `wanted`; undefined when even the
 * lowest supported one is above it, or nothing is supported.
 *
 * Rounding **down** is the cost-safe direction: someone who asked for xhigh on a model
 * without it gets high, never an unrequested max.
 */
export function clampEffort(wanted: ReasoningEffort, supported: readonly ReasoningEffort[]): ReasoningEffort | undefined {
  const rank = REASONING_EFFORTS.indexOf(wanted)
  for (let i = rank; i >= 0; i--) {
    const level = REASONING_EFFORTS[i]!
    if (supported.includes(level)) return level
  }
  return undefined
}

export interface Tokens {
  input: number
  output: number
  reasoning: number
  cache: { read: number; write: number }
  total?: number
}

// ─────────────────────────────────────────────── Requests

/** SDK-independent message shape. The agent layer builds it; the llm layer translates. */
export type LLMMessage =
  | { role: "system"; content: string }
  | { role: "user"; content: LLMContent[] }
  | { role: "assistant"; content: LLMContent[] }
  | { role: "tool"; content: LLMToolResult[] }

/** Responses identifies each assistant item separately; never infer a phase from its text. */
export interface ResponsesTextMetadata {
  itemId?: string
  phase?: "commentary" | "final_answer" | null
}

export type LLMContent =
  | { type: "text"; text: string; responses?: ResponsesTextMetadata }
  | { type: "reasoning"; text: string; signature?: string }
  | { type: "tool-call"; callID: string; tool: string; input: unknown }
  /** data is a `data:` URL. filename only labels the note sent when the model takes no images */
  | { type: "file"; mediaType: string; data: string; filename?: string }

export interface LLMToolResult {
  callID: string
  tool: string
  output: string
  isError?: boolean
}

/** Local metering identity only; never serialized into provider requests or cache scope. */
export interface AgentExecutionContext {
  requestKind: "main" | "subagent" | "title" | "compaction" | "review" | "other"
  runId: string
  sessionId?: string
  rootSessionId?: string
  /** One agent owns each stored session; these IDs use that existing identity. */
  agentInstanceId?: string
  parentAgentInstanceId?: string
  depth?: number
}

export interface LLMRequest {
  execution?: AgentExecutionContext
  model: ModelRef
  /**
   * Joined into two system messages, to keep the prompt cache prefix stable — or into one
   * where the provider sets singleSystem (openai-chat, openai-responses; see
   * toInstructions)
   */
  system: string[]
  messages: LLMMessage[]
  /**
   * Tools available this turn. They carry execute — tools are run by the LLM layer within
   * the same step; the main loop is responsible for "go another round or not", not "how
   * does this tool run".
   *
   * ToolDef itself is SDK-independent (src/tool/types.ts), so this doesn't break the
   * boundary.
   */
  tools: ToolDef<any>[]
  /**
   * Builds the context for one tool call. Injected by the agent layer; the LLM layer only
   * calls it at the right moment.
   */
  makeToolContext(call: { callID: string; abortSignal: AbortSignal }): ToolContext
  /** Subset of tools allowed this turn. Empty array = no tool calls. undefined = all. */
  activeTools?: string[]
  thinking?: boolean
  /** Unset = send nothing, the provider's default applies. See ReasoningEffort */
  effort?: ReasoningEffort
  abortSignal: AbortSignal
}

// ─────────────────────────────────────────────── Stream events

export type LLMEvent =
  | { type: "text-start"; id: string; responses?: ResponsesTextMetadata }
  | { type: "text-delta"; id: string; text: string }
  | { type: "text-end"; id: string; responses?: ResponsesTextMetadata }
  | { type: "reasoning-start"; id: string }
  | { type: "reasoning-delta"; id: string; text: string }
  | { type: "reasoning-end"; id: string; signature?: string }
  /** The model has started emitting this tool call's arguments (not complete yet) */
  | { type: "tool-input-start"; callID: string; tool: string }
  /** Arguments complete; the tool is about to run */
  | { type: "tool-call"; callID: string; tool: string; input: unknown }
  | { type: "tool-result"; callID: string; tool: string; output: string }
  | { type: "tool-error"; callID: string; tool: string; error: string }
  | { type: "step-start" }
  | { type: "step-finish"; finishReason: string; tokens: Tokens }
  | { type: "error"; error: Error }

/**
 * One stream.
 *
 * The main loop knows only this interface, not streamText — so loop.ts can be tested with
 * fake event sequences, and can later switch to our own gateway without changing a line.
 * For the real implementation see llm/stream.ts and llm/retry.ts.
 */
export interface LLMStreamHandle {
  info: ModelInfo
  events: AsyncIterable<LLMEvent>
}

export type LLMStreamFn = (request: LLMRequest) => LLMStreamHandle

// ─────────────────────────────────────────────── Errors

export class ContextOverflowError extends Error {
  constructor(message: string) {
    super(message)
    this.name = "ContextOverflowError"
  }
}

export class NoCredentialsError extends Error {
  constructor(providerID: string, hint: string) {
    super(`No credentials for provider "${providerID}": ${hint}`)
    this.name = "NoCredentialsError"
  }
}

export class UnknownModelError extends Error {
  constructor(spec: string, known: string[]) {
    super(`Unknown model "${spec}". Known providers: ${known.join(", ") || "(none registered)"}`)
    this.name = "UnknownModelError"
  }
}
