/**
 * External text may only occupy character cells; it must not move the cursor or touch
 * the clipboard. ★ Once bash previews and details are turned from JSON back into raw
 *   text, ANSI / carriage returns / tabs must be handled before wrapping, or a single
 *   progress refresh breaks LiveRegion's row-count ledger.
 * SGR generated by the theme itself isn't handled here; clean the data first, then let
 * the renderer color it.
 */
import { stripVTControlCharacters } from "node:util"
import { redact } from "../util/redact.ts"

export function terminalText(text: string): string {
  return stripVTControlCharacters(redact(text)).replace(/\r\n?/g, "\n").replace(/\t/g, "  ").replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f-\u009f]/g, "")
}
